title: "Project 2025 Assistant"
description: "A comprehensive guide to Project 2025."
baseurl: ""  # set it to your repo name if deploying on GitHub Pages
url: "https://project2025assistant.org"  # Local server address, change this to your live URL when deploying
author: "Benjamin Parsons"

collections:
  organizations:
    output: true
    permalink: /:collection/:name
  editors:
    output: true
  sections:
    output: true
  authors:
    output: true
  contributors:
    output: true
  categories:
    output: true
  questions:
    output: true

defaults:
  - scope:
      path: ""
      type: organizations
    values:
      layout: organization
  - scope:
      path: ""
      type: authors
    values:
      layout: author
  - scope:
      path: ""
      type: contributors
    values:
      layout: contributor
  - scope:
      path: ""
      type: editors
    values:
      layout: editor
  - scope:
      path: ""
      type: sections
    values:
      layout: project2025_section  # Ensure this layout exists or adjust accordingly
  - scope:
      path: ""
      type: categories
    values:
      layout: category  # Ensure this layout exists or adjust accordingly
  - scope:
      path: ""
      type: questions
    values:
      layout: question  # Ensure this layout exists or adjust accordingly
  - scope:
      path: ""  # Default scope for all pages without specific collection types
    values:
      layout: default

theme: minima  # Basic Jekyll theme for minimal aesthetics, you can customize or replace it later
