title: "Project 2025 Assistant"
description: "A comprehensive guide to Project 2025."
baseurl: ""  # Leave this blank since you're using a custom domain
url: "https://project2025assistant.org"  # Your live URL
author: "Benjamin Parsons"

collections:
  organizations:
    output: true
    permalink: /organizations/:name  # Example change for clarity
  editors:
    output: true
  sections:
    output: true
  authors:
    output: true
  contributors:
    output: true
  categories:
    output: true
  questions:
    output: true

defaults:
  - scope:
      path: ""
      type: organizations
    values:
      layout: organization
  - scope:
      path: ""
      type: authors
    values:
      layout: author
  - scope:
      path: ""
      type: contributors
    values:
      layout: contributor
  - scope:
      path: ""
      type: editors
    values:
      layout: editor
  - scope:
      path: ""
      type: sections
    values:
      layout: project2025_section
  - scope:
      path: ""
      type: categories
    values:
      layout: category
  - scope:
      path: ""
      type: questions
    values:
      layout: question
  - scope:
      path: ""  # Default scope for all pages without specific collection types
    values:
      layout: default

theme: minima  # You can customize or replace this later
