import os

# Define the directories
questions_dir = "C:/Users/SirMo/OneDrive/Documents/github/new_approach2website/website2.0/_questions"
categories_dir = "C:/Users/SirMo/OneDrive/Documents/github/new_approach2website/website2.0/_categories"

# Map question filenames to their full titles
question_map = {
    "001-federal-tax-policies": "How might Project 2025 affect federal tax policies and rates for different income brackets?",
    "002-lgbtq-rights-changes": "What changes does Project 2025 propose for LGBTQ+ rights, including marriage equality and anti-discrimination protections?",
    "003-education-reforms-impact": "How would the proposed education reforms impact public schools, universities, and student loan programs?",
    "004-womens-rights-changes": "What specific changes to women's rights are outlined in Project 2025?",
    "005-abortion-rights-reproductive-healthcare": "How does Project 2025 address abortion rights and access to reproductive healthcare?",
    "006-immigration-policies-impact": "What immigration policies are proposed, and how might they affect both legal and undocumented immigrants?",
    "007-naturalization-process-requirements": "Are there any proposed changes to the naturalization process or requirements for citizenship?",
    "008-climate-change-environmental-regulations": "How does Project 2025 approach climate change and environmental regulations?",
    "009-voting-rights-election-processes": "What changes to voting rights and election processes are proposed?",
    "010-structure-independence-federal-agencies": "How might Project 2025 affect the structure and independence of federal agencies?",
    "011-healthcare-policies-systems-changes": "What changes to healthcare policies and systems are outlined?",
    "012-racial-equity-civil-rights": "How does Project 2025 address issues of racial equity and civil rights?",
    "013-economic-policies-job-markets-wages": "What economic policies are proposed, and how might they affect job markets and wages?",
    "014-contraception-access-insurance-coverage": "How does Project 2025 address access to contraception, and what policies does it propose regarding insurance coverage for birth control methods?",
    "015-ivf-assisted-reproductive-technologies": "What stance does Project 2025 take on in vitro fertilization (IVF) and other assisted reproductive technologies, and how might its proposed policies affect access to these treatments?",
    "016-gun-laws-second-amendment-rights": "What changes to gun laws and Second Amendment rights are proposed?",
    "017-data-privacy-digital-rights": "How does Project 2025 approach issues of data privacy and digital rights?",
    "018-justice-system-law-enforcement": "What changes to the justice system and law enforcement are outlined?",
    "019-freedom-press-first-amendment-rights": "How might Project 2025 affect freedom of the press and First Amendment rights?",
    "020-labor-laws-workers-rights": "What changes to labor laws and workers' rights are proposed?",
    "021-national-security-military-policy": "How does Project 2025 address issues of national security and military policy?",
    "022-energy-policy-fossil-fuel-regulations": "What changes to energy policy and fossil fuel regulations are outlined?",
    "023-separation-church-state": "How might Project 2025 affect separation of church and state?",
    "024-antitrust-laws-corporate-regulations": "What changes to antitrust laws and corporate regulations are proposed?",
    "025-government-transparency-accountability": "How does Project 2025 approach issues of government transparency and accountability?",
    "026-changes-us-constitution": "Does Project 2025 propose any changes to the U.S. Constitution?",
    "027-wealth-inequality-poverty": "How does Project 2025 address issues of wealth inequality and poverty?",
    "028-criminal-justice-reform": "What are the proposed changes to criminal justice reform, including prison reform and sentencing guidelines?",
    "029-regulation-big-tech-digital-monopolies": "How does Project 2025 approach the regulation of big tech companies and digital monopolies?",
    "030-federal-funding-scientific-research": "What are the proposed changes to federal funding for scientific research and technological innovation?",
    "031-support-small-businesses-entrepreneurship": "How does Project 2025 plan to support small businesses and entrepreneurship?",
    "032-infrastructure-development-public-transportation": "What changes to infrastructure development and public transportation are outlined in Project 2025?",
    "033-opioid-crisis-addiction-treatment": "How does Project 2025 propose to address the opioid crisis and drug addiction treatment?",
    "034-intellectual-property-laws-patent-systems": "What are the proposed changes to intellectual property laws and patent systems?",
    "035-cybersecurity-critical-infrastructure": "How does Project 2025 address cybersecurity threats and the protection of critical infrastructure?",
    "036-agricultural-policies-support-farmers": "What changes are proposed for agricultural policies and support for farmers?",
    "037-homelessness-affordable-housing": "How does Project 2025 plan to address homelessness and affordable housing?",
    "038-veterans-benefits-support-services": "What are the proposed changes to veterans' benefits and support services?",
    "039-regulation-financial-markets-banking": "How does Project 2025 approach the regulation of financial markets and banking institutions?",
    "040-public-health-policies-epidemic-preparedness": "What changes to public health policies and epidemic preparedness are proposed?",
    "041-rights-welfare-indigenous-peoples": "How does Project 2025 address the rights and welfare of indigenous peoples?",
    "042-foreign-aid-international-development-programs": "What are the proposed changes to foreign aid and international development programs?",
    "043-national-debt-fiscal-policy": "How does Project 2025 plan to handle the national debt and fiscal policy?",
    "044-federal-judicial-system-appointment-judges": "What changes to the federal judicial system and the appointment of judges are proposed?",
    "045-public-safety-emergency-response": "How does Project 2025 propose to improve public safety and emergency response systems?",
    "046-child-welfare-family-support-programs": "What are the proposed changes to child welfare and family support programs?",
    "047-digital-education-technology-schools": "How does Project 2025 address digital education and the integration of technology in schools?",
    "048-management-preservation-national-parks": "What changes are proposed for the management and preservation of national parks and public lands?",
    "049-discrimination-gender-race-protected-characteristics": "How does Project 2025 plan to address discrimination based on gender, race, and other protected characteristics?",
    "050-retirement-savings-pension-systems": "What are the proposed changes to retirement savings and pension systems?",
    "051-international-diplomacy-conflict-resolution": "How does Project 2025 approach international diplomacy and conflict resolution?",
    "052-national-security-intelligence-agencies": "What are the proposed changes to national security and intelligence agencies?",
    "053-regulation-emerging-technologies-ai-biotech": "How does Project 2025 plan to handle the regulation of emerging technologies like AI and biotechnology?",
    "054-disaster-relief-climate-resilience-policies": "What changes are proposed for disaster relief and climate resilience policies?",
    "055-rights-protections-gig-economy-workers": "How does Project 2025 address the rights and protections of gig economy workers?",
    "056-campaign-finance-political-contributions": "What are the proposed changes to campaign finance laws and political contributions?",
    "057-ongoing-conflict-ukraine-us-involvement": "How does Project 2025 propose to handle the ongoing conflict in Ukraine? What specific policies or strategies are outlined for U.S. involvement or support?",
    "058-military-aid-ukraine": "What changes, if any, does Project 2025 suggest regarding military aid to Ukraine?",
    "059-diplomatic-relations-russia-ukraine-conflict": "How does Project 2025 approach diplomatic relations with Russia in light of the Ukraine conflict?",
    "060-nato-expansion-us-commitments-european-allies": "What stance does Project 2025 take on NATO expansion and U.S. commitments to European allies in the context of the Ukraine war?",
    "061-israel-palestine-conflict": "How does Project 2025 address the Israel-Palestine conflict, particularly in light of the recent war in Gaza?",
    "062-us-support-israel-policies": "What specific policies or approaches does Project 2025 propose regarding U.S. support for Israel?",
    "063-palestinian-rights-statehood-foreign-policy": "How does Project 2025 address Palestinian rights and statehood in its foreign policy framework?",
    "064-two-state-solution-israel-palestine-conflict": "What stance does Project 2025 take on the two-state solution for the Israel-Palestine conflict?",
    "065-balance-support-israel-humanitarian-concerns-gaza": "How does Project 2025 propose to balance support for Israel with addressing humanitarian concerns in Gaza?",
    "066-us-involvement-peace-negotiations-israel-palestine": "What approach does Project 2025 suggest for U.S. involvement in potential peace negotiations between Israel and Palestine?",
    "067-israeli-settlements-west-bank": "How does Project 2025 address the issue of Israeli settlements in the West Bank?",
    "068-us-economic-military-aid-middle-east": "What policies does Project 2025 propose regarding U.S. economic and military aid to countries in the Middle East, particularly in relation to the Israel-Palestine conflict?",
    "069-international-organizations-un-global-conflicts": "How does Project 2025 approach the role of international organizations like the UN in addressing global conflicts?",
    "070-countering-russian-influence-eastern-europe-middle-east": "What strategies does Project 2025 outline for countering Russian influence in Eastern Europe and the Middle East?",
    "071-addressing-humanitarian-crises-international-conflicts": "What strategies does Project 2025 outline for addressing humanitarian crises resulting from international conflicts?",
    "072-social-security-changes-impact-beneficiaries": "What specific changes does Project 2025 propose for Social Security, and how might these changes impact beneficiaries and the long-term sustainability of the program?",
    "073-medicare-reform-healthcare-access-quality": "How does Project 2025 propose to reform Medicare, and what are the potential impacts on healthcare access, costs, and quality for seniors and other eligible populations?",
    "074-medicaid-reforms-low-income-individuals-families": "What reforms to Medicaid are outlined in Project 2025, and how might these changes affect low-income individuals and families who rely on the program for healthcare coverage?",
    "075-legalization-marijuana-policies": "What is Project 2025’s stance on the legalization of marijuana, and how might its proposed policies impact federal and state-level legalization efforts, criminal justice reform, and public health?",
    "076-expanding-limiting-emergency-powers-president": "How does Project 2025 propose to expand or limit the use of emergency powers by the President, and what safeguards are in place to prevent abuse of executive authority under the immunity ruling?",
    "077-federal-judiciary-structure-composition-changes": "Does Project 2025 suggest any changes to the structure or composition of the federal judiciary, including the possibility of court-packing or limiting judicial review?",
    "078-schedule-f-changes-implementation": "What is 'Schedule F,' and what changes does Project 2025 propose regarding its implementation?",
    "079-schedule-f-impact-federal-civil-service": "How would the implementation of Schedule F impact the structure and independence of the federal civil service?",
    "080-schedule-f-risks-benefits-implementation": "What are the potential risks and benefits of implementing Schedule F as outlined in Project 2025?",
    "081-schedule-f-executive-branch-federal-agencies": "How might Schedule F, if implemented, affect the balance of power between the executive branch and federal agencies?",
    "082-schedule-f-safeguards-prevent-abuse-power": "What safeguards, if any, does Project 2025 propose to prevent the abuse of power under Schedule F?",
    "083-federal-state-local-governments-relationship-changes": "How does Project 2025 propose to change the relationship between federal, state, and local governments, and what are the potential impacts on federalism and states' rights?",
    "084-public-health-policies-vaccinations": "What stance does Project 2025 take on public health policies, particularly regarding mandatory vaccinations and government-mandated health measures during pandemics?",
    "085-intellectual-freedom-education": "How does Project 2025 address the issue of intellectual freedom in education, particularly regarding censorship or control over educational content in schools and universities?",
    "086-reforming-us-criminal-justice-system": "How does Project 2025 propose to reform the U.S. criminal justice system, particularly in relation to mass incarceration and mandatory minimum sentences?",
    "087-federal-surveillance-programs-civil-liberties": "What changes does Project 2025 suggest for federal surveillance programs and their impact on civil liberties?",
    "088-racial-profiling-law-enforcement": "How does Project 2025 address the issue of racial profiling and law enforcement practices?",
    "089-voting-rights-voter-id-laws-polling-access": "What is Project 2025's stance on federal protections for voting rights, particularly in relation to voter ID laws and access to polling places?",
    "090-us-relations-china-trade-technology-human-rights": "How does Project 2025 propose to handle relations with China, especially regarding trade, technology, and human rights issues?",
    "091-us-relationship-nato-military-alliances": "What strategies does Project 2025 outline for managing the U.S. relationship with NATO and other military alliances?",
    "092-us-foreign-aid-africa-combating-poverty-disease-conflict": "How does Project 2025 approach U.S. foreign aid to Africa and its role in combating poverty, disease, and conflict on the continent?",
    "093-environmental-protection-clean-water-air-standards": "What are the proposed changes to federal regulations on environmental protection, particularly concerning clean water and air standards?",
    "094-urbanization-affordable-housing-infrastructure-development": "How does Project 2025 plan to address the challenges of urbanization, including affordable housing and infrastructure development in cities?",
    "095-public-sector-unions-workers-bargaining-rights": "What changes does Project 2025 propose for public sector unions and workers' collective bargaining rights?",
    "096-cybersecurity-critical-infrastructure-protection": "How does Project 2025 plan to address cybersecurity for critical infrastructure, including power grids, financial systems, and communication networks?",
    "097-us-nuclear-arsenal-arms-control-agreements": "What is Project 2025's stance on the U.S. nuclear arsenal and the future of arms control agreements?",
    "098-opioid-crisis-pharmaceutical-regulations-addiction-treatment": "How does Project 2025 address the opioid crisis, particularly regarding pharmaceutical regulations and addiction treatment programs?",
    "099-healthcare-access-marginalized-communities": "What are the proposed changes to healthcare access for marginalized communities, including the uninsured and underinsured?",
    "100-financial-institutions-regulation-economic-crises": "How does Project 2025 approach the regulation of financial institutions in the wake of economic crises?",
    "101-income-inequality-corporate-taxes-wealth-redistribution": "What strategies does Project 2025 outline for dealing with income inequality, particularly in relation to corporate taxes and wealth redistribution?",
    "102-us-relations-latin-american-countries": "How does Project 2025 plan to handle U.S. relations with Latin American countries, particularly regarding immigration and trade?",
    "103-endangered-species-biodiversity-conservation": "What is Project 2025's stance on federal protections for endangered species and biodiversity conservation?",
    "104-us-tax-code-corporate-taxes-loopholes": "How does Project 2025 propose to reform the U.S. tax code, particularly in relation to corporate taxes and loopholes?",
    "105-campaign-finance-dark-money-politics": "What changes does Project 2025 suggest for regulating campaign finance, particularly regarding the influence of dark money in politics?",
    "106-healthcare-affordability-access-rural-areas": "How does Project 2025 address the issue of healthcare affordability and access, particularly in rural areas?",
    "107-us-leadership-global-health-initiatives": "What is Project 2025's approach to U.S. leadership in global health initiatives, particularly regarding pandemic preparedness?",
    "108-us-energy-independence-environmental-concerns": "How does Project 2025 plan to manage U.S. energy independence while addressing environmental concerns?",
    "109-federal-disaster-response-climate-emergencies": "What are the proposed changes to federal disaster response policies, particularly in relation to climate-related emergencies?",
    "110-housing-affordability-homelessness-suburban-rural": "How does Project 2025 address the issue of housing affordability and homelessness in suburban and rural areas?",
    "111-national-debt-fiscal-responsibility": "What strategies does Project 2025 propose for managing the national debt and fiscal responsibility?",
    "112-pharmaceutical-industry-regulation-drug-pricing-safety": "How does Project 2025 approach the regulation of the pharmaceutical industry, particularly concerning drug pricing and safety?",
    "113-public-land-management-national-parks-wilderness-areas": "What changes does Project 2025 propose for public land management, including national parks and wilderness areas?",
    "114-economic-mobility-american-dream-low-income-families": "How does Project 2025 plan to address the issue of economic mobility and the American Dream, particularly for low-income families?",
    "115-gasoline-prices-energy-policies-impact": "How does Project 2025 propose to address gasoline prices, and what impact might its energy policies have on fuel costs, domestic production, and consumers?",
    "116-trade-policies-economic-strategies-us-economy": "What trade policies and economic strategies does Project 2025 propose, and how might these affect the U.S. economy, international trade relations, and consumer prices?",
    "117-job-creation-manufacturing-industrial-sectors": "What specific strategies does Project 2025 outline for creating jobs in the U.S., particularly in manufacturing and industrial sectors, and how does it plan to bring back jobs that have been outsourced overseas?",
    "118-protection-civil-liberties-national-crises": "How does Project 2025 address the protection of civil liberties, such as freedom of speech, assembly, and due process, during national crises or periods of unrest?",
    "119-safeguards-prevent-political-retaliation-partisan-purposes": "What safeguards does Project 2025 propose to prevent the use of federal agencies, such as the IRS, DOJ, or FBI, for political retaliation or partisan purposes?",
    "120-protection-minority-rights-majoritarian-rule": "How does Project 2025 address the protection of minority rights, particularly in the context of potential majoritarian rule and the erosion of checks and balances?",
    "121-regulation-independent-media-freedom-press-journalism": "Does Project 2025 propose any changes to the regulation of independent media, and how might these changes affect freedom of the press and the role of journalism in a democratic society?",
    "122-transparency-accountability-government-decisions": "What measures does Project 2025 propose to ensure transparency and accountability in government decision-making, particularly regarding executive actions that may be shielded by the immunity ruling?",
    "123-social-media-regulation": "How does Project 2025 propose to address the future of social media regulation, particularly concerning misinformation, censorship, and platform accountability?",
    "124-electoral-college-presidential-elections": "Does Project 2025 propose any changes to the Electoral College system or the process of presidential elections?",
    "125-mental-health-services-policies": "What are the proposed changes to mental health services and policies in Project 2025, particularly concerning access, funding, and integration with other healthcare services?",
    "126-regulation-private-military-contractors": "How does Project 2025 approach the regulation of private military contractors and their role in U.S. military operations?",
    "127-intellectual-property-theft-cyber-espionage": "How does Project 2025 propose to handle issues of intellectual property theft and cyber-espionage, particularly by foreign actors?",
    "128-disaster-resilience-climate-adaptation-infrastructure": "What strategies does Project 2025 outline for improving disaster resilience in communities vulnerable to natural disasters, particularly in relation to climate adaptation and infrastructure development?",
    "129-future-space-exploration-national-security": "How does Project 2025 approach the future of space exploration and national security in space, particularly regarding public-private partnerships and international competition?",
    "130-altering-balance-power-between-branches": "How does Project 2025 propose to alter the balance of power between the executive, legislative, and judicial branches?",
    "131-impeachment-process-executive-accountability": "Are there any proposed changes to the impeachment process or other mechanisms for holding the executive accountable?",
    "132-election-administration-voter-registration-mail-in-voting": "What specific measures does Project 2025 propose regarding election administration, voter registration, and mail-in voting?",
    "133-voter-suppression-gerrymandering-concerns": "How does it address concerns about voter suppression and gerrymandering?",
    "134-disinformation-campaigns": "Does Project 2025 propose any measures to combat or potentially exploit disinformation campaigns?",
    "135-media-ownership-public-broadcasting-regulations": "Are there plans to change regulations on media ownership or public broadcasting?",
    "136-military-forces-domestic-purposes": "How does Project 2025 address the use of military forces for domestic purposes, such as protest control or border enforcement?",
    "137-withdrawal-international-agreements-organizations": "Does Project 2025 propose withdrawing from any international agreements or organizations?",
    "138-international-treaties-ratification-adherence": "How does Project 2025 approach the ratification and adherence to international treaties?",
    "139-cryptocurrency-regulation-us-digital-dollar": "What is Project 2025's stance on cryptocurrency regulation and the potential for a U.S. digital dollar?",
    "140-whistleblower-protections-government-employees": "How does Project 2025 address whistleblower protections, especially for government employees?",
    "141-presidential-pardon-power-changes": "Does Project 2025 propose any changes to the presidential pardon power, especially in light of the immunity ruling?",
    "142-use-eminent-domain-federal-projects-private-development": "How does Project 2025 approach the use of eminent domain for federal projects or private development?",
    "143-federal-education-funding-public-private-schools": "Are there proposed changes to how federal education funding is allocated, particularly regarding public vs. private schools?",
    "144-systemic-racism-american-institutions": "How does Project 2025 propose to address systemic racism in American institutions, including law enforcement, education, healthcare, and housing? What specific policies or reforms, if any, does it outline to promote racial equity and combat discriminatory practices?",
    "145-future-pandemics-public-health-emergencies": "How does Project 2025 propose to handle future pandemics or public health emergencies, particularly regarding federal vs. state authority?",
    "146-regulation-banning-pornography": "What specific measures does Project 2025 propose regarding the regulation or banning of pornography, and how might these measures affect the industry and access to adult content?",
    "147-privatization-federal-services-impact-access": "What proposals does Project 2025 offer regarding the privatization of federal services, and how might these policies impact public access to essential government functions?",
    "148-international-relations-trade-agreements-impact": "How might Project 2025 affect international relations and trade agreements?",
    "149-conflicts-interest-government-contracts-private-corporations": "How does Project 2025 address the potential conflicts of interest within government contracts, particularly in relation to the influence of private corporations in public policy-making?",
    "150-regulation-labor-unions-collective-bargaining": "What changes does Project 2025 suggest for the regulation of labor unions, and could these proposals weaken collective bargaining rights and worker protections?",
    "151-regulation-pharmaceutical-industry-drug-pricing-safety": "How does Project 2025 propose to handle the regulation of the pharmaceutical industry in terms of drug development and pricing, and could these policies lead to reduced access to affordable medication?",
    "152-federal-funding-arts-culture-programs": "What stance does Project 2025 take on the federal funding of arts and culture programs, and could its proposed policies lead to decreased support for the arts in public education and community development?",
    "153-antitrust-enforcement-large-corporations": "How might Project 2025’s approach to antitrust enforcement affect the concentration of power among large corporations, and what could be the implications for competition and consumer choice?",
    "154-public-broadcasting-management": "What proposals does Project 2025 make regarding the management of public broadcasting services, and how might these changes impact the independence and reach of non-commercial media?",
    "155-civil-asset-forfeiture-potential-abuse": "How does Project 2025 address the issue of civil asset forfeiture, and could its policies exacerbate the potential for abuse in law enforcement practices?",
    "156-surveillance-technology-consumer-privacy-data-security": "What specific measures does Project 2025 propose to address the use of surveillance technology by private companies, and how might these policies affect consumer privacy and data security?",
    "157-reforming-disaster-relief-programs": "How does Project 2025 propose to reform disaster relief programs, particularly in terms of federal versus private sector roles, and could these changes lead to inequities in disaster recovery efforts?",
    "158-gender-equity-education-employment-healthcare": "How does Project 2025 address the issue of gender equity in education, employment, and healthcare?",
    "159-public-land-management-cultural-significance-indigenous-communities": "How does Project 2025 propose to manage public lands, including national parks and wilderness areas, that are of cultural significance to indigenous communities?",
    "160-economic-development-resource-extraction-indigenous-lands": "What policies does Project 2025 propose regarding economic development and resource extraction on indigenous lands?"
}

# Define the categories and their associated question filenames
categories = {
    "Censorship": [
        "085-intellectual-freedom-education",
        "121-regulation-independent-media-freedom-press-journalism",
        "134-disinformation-campaigns",
        "135-media-ownership-public-broadcasting-regulations",
        "146-regulation-banning-pornography",
        "154-public-broadcasting-management",
    ],
    "Child Welfare and Family Support": [
        "046-child-welfare-family-support-programs"
    ],
    "Civil Rights and Liberties": [
        "012-racial-equity-civil-rights",
        "144-systemic-racism-american-institutions",
        "158-gender-equity-education-employment-healthcare"
    ],
    "Corporate Regulation": [
        "024-antitrust-laws-corporate-regulations",
        "153-antitrust-enforcement-large-corporations",
    ],
    "Criminal Justice": [
        "018-justice-system-law-enforcement",
        "028-criminal-justice-reform",
        "086-reforming-us-criminal-justice-system",
        "088-racial-profiling-law-enforcement",
        "155-civil-asset-forfeiture-potential-abuse",
    ],
    "Economic Policy": [
        "001-federal-tax-policies",
        "013-economic-policies-job-markets-wages",
        "027-wealth-inequality-poverty",
        "030-federal-funding-scientific-research",
        "116-trade-policies-economic-strategies-us-economy",
    ],
    "Education": [
        "003-education-reforms-impact",
        "047-digital-education-technology-schools",
        "143-federal-education-funding-public-private-schools",
    ],
    "Energy Policy": [
        "022-energy-policy-fossil-fuel-regulations",
        "108-us-energy-independence-environmental-concerns",
    ],
    "Environment and Climate Change": [
        "008-climate-change-environmental-regulations",
        "036-agricultural-policies-support-farmers",
        "048-management-preservation-national-parks",
        "093-environmental-protection-clean-water-air-standards",
    ],
    "First Amendment Rights": [
        "019-freedom-press-first-amendment-rights",
        "023-separation-church-state",
    ],
    "Foreign Policy and International Relations": [
        "051-international-diplomacy-conflict-resolution",
        "061-israel-palestine-conflict",
        "062-us-support-israel-policies",
        "064-two-state-solution-israel-palestine-conflict",
        "070-countering-russian-influence-eastern-europe-middle-east",
        "148-international-relations-trade-agreements-impact",
        "071-addressing-humanitarian-crises-international-conflicts",
        "126-regulation-private-military-contractors",
        "097-us-nuclear-arsenal-arms-control-agreements",
    ],
    "Government Structure and Powers": [
        "010-structure-independence-federal-agencies",
        "017-data-privacy-digital-rights",
        "054-disaster-relief-climate-resilience-policies",
        "076-expanding-limiting-emergency-powers-president",
        "077-federal-judiciary-structure-composition-changes",
        "120-protection-minority-rights-majoritarian-rule",
        "130-altering-balance-power-between-branches",
    ],
    "Government Transparency and Accountability": [
        "025-government-transparency-accountability",
        "122-transparency-accountability-government-decisions",
    ],
    "Gun Policies": [
        "016-gun-laws-second-amendment-rights",
    ],
    "Healthcare and Public Health": [
        "011-healthcare-policies-systems-changes",
        "014-contraception-access-insurance-coverage",
        "015-ivf-assisted-reproductive-technologies",
        "033-opioid-crisis-addiction-treatment",
        "040-public-health-policies-epidemic-preparedness",
        "073-medicare-reform-healthcare-access-quality",
        "074-medicaid-reforms-low-income-individuals-families",
        "075-legalization-marijuana-policies",
        "098-opioid-crisis-pharmaceutical-regulations-addiction-treatment",
        "099-healthcare-access-marginalized-communities",
    ],
    "Immigration and Citizenship": [
        "006-immigration-policies-impact",
        "007-naturalization-process-requirements",
        "102-us-relations-latin-american-countries",
    ],
    "Indigenous Peoples' Rights": [
        "041-rights-welfare-indigenous-peoples",
        "159-public-land-management-cultural-significance-indigenous-communities",
        "160-economic-development-resource-extraction-indigenous-lands"
    ],
    "Infrastructure and Housing": [
        "032-infrastructure-development-public-transportation",
        "037-homelessness-affordable-housing",
        "110-housing-affordability-homelessness-suburban-rural",
    ],
    "Israel/Palestine Conflict": [
        "061-israel-palestine-conflict",
        "062-us-support-israel-policies",
        "063-palestinian-rights-statehood-foreign-policy",
        "064-two-state-solution-israel-palestine-conflict",
        "065-balance-support-israel-humanitarian-concerns-gaza",
        "066-us-involvement-peace-negotiations-israel-palestine",
        "067-israeli-settlements-west-bank",
    ],
    "Judicial System": [
        "044-federal-judicial-system-appointment-judges",
    ],
    "Labor and Workers' Rights": [
        "020-labor-laws-workers-rights",
        "055-rights-protections-gig-economy-workers",
        "095-public-sector-unions-workers-bargaining-rights",
        "150-regulation-labor-unions-collective-bargaining",
    ],
    "LGBTQ+ Rights": [
        "002-lgbtq-rights-changes",
    ],
    "Marijuana Policy": [
        "075-legalization-marijuana-policies",
    ],
    "National Security and Military": [
        "021-national-security-military-policy",
        "052-national-security-intelligence-agencies",
        "126-regulation-private-military-contractors",
        "097-us-nuclear-arsenal-arms-control-agreements",
    ],
    "Russia/Ukraine Conflict": [
        "057-ongoing-conflict-ukraine-us-involvement",
        "058-military-aid-ukraine",
        "059-diplomatic-relations-russia-ukraine-conflict",
        "060-nato-expansion-us-commitments-european-allies",
        "070-countering-russian-influence-eastern-europe-middle-east",
    ],
    "Schedule F": [
        "078-schedule-f-changes-implementation",
        "079-schedule-f-impact-federal-civil-service",
        "080-schedule-f-risks-benefits-implementation",
        "081-schedule-f-executive-branch-federal-agencies",
        "082-schedule-f-safeguards-prevent-abuse-power",
    ],
    "Science and Technology": [
        "034-intellectual-property-laws-patent-systems",
        "053-regulation-emerging-technologies-ai-biotech",
    ],
    "Social Security, Medicare, and Medicaid": [
        "072-social-security-changes-impact-beneficiaries",
        "073-medicare-reform-healthcare-access-quality",
        "074-medicaid-reforms-low-income-individuals-families",
    ],
    "Systemic Racism and Minority Rights": [
        "012-racial-equity-civil-rights",
        "144-systemic-racism-american-institutions",
        "120-protection-minority-rights-majoritarian-rule",
    ],
    "Veterans' Affairs": [
        "038-veterans-benefits-support-services",
    ],
    "Voting Rights and Election Processes": [
        "009-voting-rights-election-processes",
        "089-voting-rights-voter-id-laws-polling-access",
        "124-electoral-college-presidential-elections",
        "132-election-administration-voter-registration-mail-in-voting",
        "133-voter-suppression-gerrymandering-concerns",
    ],
    "Women's Rights": [
        "004-womens-rights-changes",
        "005-abortion-rights-reproductive-healthcare",
        "014-contraception-access-insurance-coverage",
        "015-ivf-assisted-reproductive-technologies",
    ]
}

def generate_category_content(category_name, question_files):
    content = f"---\nlayout: category\ntitle: {category_name}\n---\n\n# {category_name}\n\n## Questions\n\n"
    for question_file in question_files:
        question_title = question_map[question_file]
        question_link = f"/questions/{question_file}.html"
        content += f"- [{question_title}]({question_link})\n"
    return content

def create_category_files(categories):
    for category, question_files in categories.items():
        category_filepath = os.path.join(categories_dir, f"{category.lower().replace(' ', '-').replace('/', '-')}.md")
        content = generate_category_content(category, question_files)
        with open(category_filepath, 'w', encoding='utf-8') as file:
            file.write(content)

# Execute the function to create category files
create_category_files(categories)
